### ISSUE TITLE
All in One

### ISSUE THREAD

**Issue by igromanru** [Synthlight/Reactor-Count-Mod#1]
Hi, thank you for your mods.   
I see that you have all the code in one repo project. Might it be possible to release a "All in One" mod, for people like me, who use all of them? So we don't have to update 6 mods each time.  
And maybe, but just maybe, if you want to go further. You could make features toggles in a ini/toml file.

**Comment by Synthlight** [comment]
I will not and why has been explained in the FAQ of *any* of the mods' stickied comments.
There's also a collection Vortex users can use which is *also* in the same place in the FAQ.

Copied here:
![image](https://github.com/Synthlight/Reactor-Count-Mod/assets/1075166/133067e9-324b-4785-86b8-a6d611343eb3)
